### ISSUE TITLE
Arrows not working on the web with Google Fonts

### ISSUE THREAD

**Issue by MattMcAdams** [thundernixon/recursive#534]
**Problem description**

When using the font through google fonts on the web, the arrows will not display as this font's characters.

**Expected behavior**

The arrows should use the characters from this font

**Screenshots**

<img width="776" alt="Screenshot 2024-02-29 at 4 12 03 PM" src="https://github.com/arrowtype/recursive/assets/26938709/ab74c1bf-00a7-4f97-bac8-1718591f11b9">

**To Reproduce**

I've made a codepen that shows this issue: https://codepen.io/mattmcadams/pen/mdgdKZL

**Environment (please complete the following information):**

- OS: MacOS 13.5.1
- Browser: Firefox Dev Edition 124.0b3
- Fonts: Google fonts? I'm not sure

**Additional context**

I've tried passing the actual arrow characters into my code `→` and `←` and using the `&larr;` and `&rarr;` sequences.

My CSS looks like this:

```css
@import url('https://fonts.googleapis.com/css2?family=Recursive:slnt,wght,CRSV,MONO@-15..0,300..800,0..1,0..1&display=swap');

body {
  font-family: 'Recursive', 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
}
```

I've tried to search around for an answer but I've come up empty, but I haven't tried self-hosting the font yet, so I'll try that next.

I don't know if this is a legitimate bug or if there are extra steps I need to do to get these characters. Thanks for any assistance, and thanks for the incredible typeface!
